name: 🌐 Link
description: Create a new Link item
title: "<Link Title>"
labels: ["content:link"]
body:
- type: input
  attributes:
    label: URL
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
  validations:
    required: false
