name: ✏️ Post
description: Create a new post
title: "Post"
labels: ["content:post","status:draft"]
body:
- type: input
  id: publishDate
  attributes:
    label: Publish Date
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
  validations:
    required: true
